<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{{ $report_name }}</title>
</head>

<body>
    <div class="container-fluid mt-5 mb-3">
        <div class="row d-flex justify-content-center">
            <div class="col-10">
                <div class="card">
                    <div class="d-flex flex-row p-2">
                        <!-- <img src="https://i.imgur.com/vzlPPh3.png" width="48"> -->
                        <div class="d-flex flex-column">
                            <h4>{{ config('app.name') }}</h4>
                            <span class="font-weight-bold">Commission Report</span>
                        </div>
                    </div>
                    <hr>
                    <div class="table-responsive p-2">
                        <table class="table table-borderless">
                            <tbody>
                                <tr class="add">
                                    <td>Generated By: {{ $user->name }}</td>
                                    <td>Generated On: {{ now()->toDateTimeString() }}</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                    <hr>
                    <div class="products p-2">
                        <table class="table table-borderless">
                            <tbody>
                                <tr class="content">
                                    <td>Salesperson</td>
                                    <td>{{ $transaction_user['user']['name'] }}</td>
                                </tr>
                                <tr class="content">
                                    <td style="padding-bottom: 20px;">Property Address</td>
                                    <td>{{ $transaction_user['transaction']['property']['address'] }}</td>
                                </tr>
                                <tr>
                                    <td></td>
                                </tr>
                                <tr class="content">
                                    <td>Commission (%)</td>
                                    <td>{{ $transaction_user['percentage'] }}</td>
                                </tr>
                                <tr class="content">
                                    <td>Sale@Lease price ($)</td>
                                    <td>{{ number_format( $transaction_user['transaction']['price'], 2, '.', ',') }}</td>
                                </tr>
                                <tr class="add">
                                    <td>Calculation</td>
                                    <td>
                                        <span>( Commission / 100 ) * ( Sale@Lease price )</span><br>
                                        <!-- <span>( {{$transaction_user['percentage']}} / 100 ) * ( {{ $transaction_user['transaction']['price'] }} )</span> -->
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <hr>
                    <div class="products p-2">
                        <table class="table table-borderless">
                            <tbody>
                                <tr class="add">
                                    <td><strong>Total Commission Received</strong></td>
                                    <td><strong>$ {{ number_format( $transaction_user['commission'], 2, '.', ',') }}</strong></td>
                                    <!-- <td>Subtotal</td>
                                    <td>GST(10%)</td>
                                    <td class="text-center">Total</td> -->
                                </tr>
                                <tr class="content">
                                    <!-- <td>$40,000</td>
                                    <td>2,500</td>
                                    <td class="text-center">$42,500</td> -->
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <!-- <hr>
                    <div class="address p-2">
                        <table class="table table-borderless">
                            <tbody>
                                <tr class="add">
                                    <td>Bank Details</td>
                                </tr>
                                <tr class="content">
                                    <td> Bank Name : ADS BANK <br> Swift Code : ADS1234Q <br> Account Holder : Jelly Pepper <br> Account Number : 5454542WQR <br> </td>
                                </tr>
                            </tbody>
                        </table>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</body>